name: Java With Maven
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        working-directory: ./demo
        run: mvn compile --file pom.xml
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        working-directory: ./demo
        run: mvn compile --file pom.xml
  docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build PDF with Maven
        working-directory: ./demo
        run: mvn pdf:pdf --file pom.xml
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: demo/target/pdf/demo.pdf
