name: Java With Maven
on: [push, pull_request]
jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        working-directory: ./demo
        run: mvn compile --file pom.xml
